name: Deploy Workflow

on:  
  workflow_dispatch: 
  workflow_run:
    workflows: ["Test workflow"]  # 依存するワークフローの名前
    types:
      - completed  # ワークフローが完了した時にトリガー
    conclusion: success  # 成功した場合にのみ実行


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: echo "Deploying application..."
