name: Example Workflow

on:
  workflow_dispatch:

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for completion artifact
        run: |
          if [ ! -f completion_artifact.txt ]; then
            echo "Another Workflow has not completed."
            exit 1
          fi

      - name: Run a script
        run: echo "Hello, world!"
      - name: Delete completion artifact
        run: rm completion_artifact.txt
