name: Test workflow 
on: 
  pull_request:
    paths: ['django/**' ]
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${BRANCH}"     # シェルコマンドからジョブレベルの環境変数を参照
