name: Test workflow
on: 
  push:
    paths: ['django/**' ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${BRANCH}"     # シェルコマンドからジョブレベルの環境変数を参照
      - name: Sleep for 10 seconds
        run: sleep 10  # 10秒間スリープ
